# Site settings
title: Ryan Scarpelli's Personal Website
email: Ryan.Scarpelli@gmail.com
description: Ryan's Personal Website
url: ryanscarpelli.github.io
github_username: ryanscarpelli

# Build settings
markdown: kramdown
permalink: pretty